/*
 * XXX API
 *
 * XXXについてのAPI
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// LoginApiRouter defines the required methods for binding the api requests to a responses for the LoginApi
// The LoginApiRouter implementation should parse necessary information from the http request,
// pass the data to a LoginApiServicer to perform the required actions, then write the service results to the http response.
type LoginApiRouter interface { 
	StartLogin(http.ResponseWriter, *http.Request)
}


// LoginApiServicer defines the api actions for the LoginApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type LoginApiServicer interface { 
	StartLogin(context.Context, LoginBody) (ImplResponse, error)
}
