/*
 * XXX API
 *
 * XXXについてのAPI
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// LoginApiService is a service that implements the logic for the LoginApiServicer
// This service should implement the business logic for every endpoint for the LoginApi API.
// Include any external packages or services that will be required by this service.
type LoginApiService struct {
}

// NewLoginApiService creates a default api service
func NewLoginApiService() LoginApiServicer {
	return &LoginApiService{}
}

// StartLogin - Login
func (s *LoginApiService) StartLogin(ctx context.Context, loginBody LoginBody) (ImplResponse, error) {
	// TODO - update StartLogin with the required logic for this service method.
	// Add api_login_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, DefaultErrorResponse{}) or use other options such as http.Ok ...
	//return Response(400, DefaultErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("StartLogin method not implemented")
}
