/*
 * XXX API
 *
 * XXXについてのAPI
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DefaultErrorResponseErrorsInner struct {

	Message string `json:"message"`

	Detail map[string]interface{} `json:"detail,omitempty"`
}

// AssertDefaultErrorResponseErrorsInnerRequired checks if the required fields are not zero-ed
func AssertDefaultErrorResponseErrorsInnerRequired(obj DefaultErrorResponseErrorsInner) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDefaultErrorResponseErrorsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DefaultErrorResponseErrorsInner (e.g. [][]DefaultErrorResponseErrorsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDefaultErrorResponseErrorsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDefaultErrorResponseErrorsInner, ok := obj.(DefaultErrorResponseErrorsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDefaultErrorResponseErrorsInnerRequired(aDefaultErrorResponseErrorsInner)
	})
}
