/*
 * XXX API
 *
 * XXXについてのAPI
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	LoginApiService := openapi.NewLoginApiService()
	LoginApiController := openapi.NewLoginApiController(LoginApiService)

	router := openapi.NewRouter(LoginApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
